### ISSUE TITLE
Missing user.css and user.js

### ISSUE THREAD

**Issue by martinvelez** [chjj/tty.js#126]
In static/index.html, you include user.css.  However, that file does not exist in this repo.  Is it needed?

The same is true for user.js.

**Comment by marcysutton** [comment]
It would be helpful to see an example of how you include those files.

**Comment by howardroark** [comment]
Maybe comment them out or include empty files with commented examples like your gist?  

This threw me off too, just don't expect to see 404 errors.  I don't think too many developers need to be informed that they can add js/css to html.

**Comment by risacher** [comment]
If user.css and user.js were included as blank files, then package upgrades would constantly ask you if you want to keep your customized versions or overwrite with the package's versions.  On the other hand, if the includes were not in the static/index.html, the same problem would arise with that file when you customize it to include your css.

Personally, I *like* the way Chris set this up.  I think the 404 errors in the log actually is what inspired me to customize my tty.js configuration...  

But I can see the other side.  Maybe a slick solution would be to not include the files in the package, but create empty files at startup if they don't exist?

**Comment by howardroark** [comment]
Ahhhh ok... Yeah I am new to node and I see what you are saying.  If you get understand npm... you get how those files are dealt with.  Makes sense to me. 

If a common node user see the 404 they think... "Hey I could make my own!".  Yeah I get that :)
