### ISSUE TITLE
Not compiling on 0.10.33

### ISSUE THREAD

**Issue by derekcollison** [chjj/tty.js#129]
> npm install tty.js
> 
> pty.js@0.2.3 install /Users/derek/Development/node_modules/tty.js/node_modules/pty.js
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o
../src/unix/pty.cc:499:10: error: use of undeclared identifier 'openpty'
  return openpty(amaster, aslave, name, (termios _)termp, (winsize *)winp);
         ^
../src/unix/pty.cc:545:10: error: use of undeclared identifier 'forkpty'
  return forkpty(amaster, name, (termios *)termp, (winsize *)winp);
         ^
2 errors generated.
make: *_\* [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/derek/.nvm/v0.10.33/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/Users/derek/.nvm/v0.10.33/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/derek/Development/node_modules/tty.js/node_modules/pty.js
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

> ws@0.4.32 install /Users/derek/Development/node_modules/tty.js/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
npm ERR! pty.js@0.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.3 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.0.0
npm ERR! command "/Users/derek/.nvm/v0.10.33/bin/node" "/Users/derek/.nvm/v0.10.33/bin/npm" "install" "tty.js"
npm ERR! cwd /Users/derek/Development/go/src/github.com/jwilder/docker-squash
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by OKNoah** [comment]
Same issue here.

**Comment by jedverity** [comment]
+1

**Comment by elliottsj** [comment]
Got it working on OS X by [using the master branch of pty.js](https://github.com/elliottsj/tty.js/commit/b1ea6376d4ba7ce7dc883a514b046f02d1f4c6af).
