### ISSUE TITLE
Failed to install tty.js with npm

### ISSUE THREAD

**Issue by rhysd** [chjj/tty.js#146]
I tried to install tty.js

```sh
$ npm install tty.js
```

But I got an error as below.

```
npm ERR! Linux 3.2.0-84-generic-pae
npm ERR! argv "/home/hayashida/.nvm/versions/node/v0.12.7/bin/node" "/home/hayashida/.nvm/versions/node/v0.12.7/bin/npm" "install" "tty.js"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! version not found: pty.js@0.2.7
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hayashida/Programs/ttyjstest/npm-debug.log
```

Is package dependency broken?
My environment is:

- npm 2.11.3
- Ubuntu Linux
- Node.js v0.12.7

npm-debug.log is [here](https://gist.github.com/rhysd/4cdf4474ff784c322cf4).

**Comment by G07cha** [comment]
I have accured same problem and created pull request, hope @chjj will approve merge it soon

**Comment by kernelt** [comment]
Hi! We have exactly same bug. Can you fix it as soon as possible?

**Comment by rhysd** [comment]
@G07cha 

Thank you for your fix.  I wait @chjj will marge.


@kernelt 

See #147.

**Comment by G07cha** [comment]
Actually you can install from [my fork](https://github.com/G07cha/tty.js):
```bash
npm install -g https://github.com/G07cha/tty.js.git
```
But if you want to recieve future updates keep eye on my pull request and this issue. If issue will be closed you can switch back to original repository.

**Comment by chjj** [comment]
It was still using an old version of pty.js (which for some reason was removed from npm? not sure). Should be fixed now.

**Comment by G07cha** [comment]
Thanks, closing my pull request

**Comment by rhysd** [comment]
:tada:

**Comment by chjj** [comment]
Oh, this new version of pty.js also solves the zombie process problem that initially started ocurring in node >0.8.0.
