### ISSUE TITLE
Support copy/paste

### ISSUE THREAD

**Issue by acertain** [chjj/tty.js#17]
Preferably through the browser

**Comment by anthony-o** [comment]
Still an issue, but thanks to https://gist.github.com/risacher/7837761 I managed to workaround this on Firefox on Windows.

**Comment by jmls** [comment]
I can't get this to work on chrome-51 

is there a solution that works like cloud9 copy/paste (ctrl-c / ctrl-v)

**Comment by wlLeblanc** [comment]
@chjj  Hello  I am using your term. Js plug-in terminal, I'd like to start out as a cursor, click go terminal cursor. How to deal with this?

**Comment by Airstriker** [comment]
To enable copy and paste functionality (it's disabled by default), you need to add **screenKeys: true** to the tty configuration, like in the example below:
```
var app = tty.createServer({
      shell: 'bash',
      shellArgs: ["ll"],
      port: 4444,
      term: {
        termName: "xterm",
        geometry: [106, 27],
        screenKeys: true,
        cursorBlink: true
      }
    });
```
Then simply:
- mark the text with the mouse
- ctr + a (enters prefix mode)
- ctr + c (copy)
- ctr + v (paste)

Works in every environment (Windows, Linux etc.).
