### ISSUE TITLE
Copy/Paste is not working in firefox at all

### ISSUE THREAD

**Issue by pstjvn** [chjj/tty.js#30]
There is no way to copy./paste in the terminal in firefox. I tried the following:
select from the output and press middle button - not working
select from output, right click -> Copy, right click -> Paste - not working
select text with the mouse, ctrl C + ctrl V - not working

middle mouse button works in Chrome, unfortunately I cannot use chrome on some machines. Would that be fixed in FF?

**Comment by anthony-o** [comment]
Still an issue 4 years later, but thanks to https://gist.github.com/risacher/7837761 I managed to workaround this.
