### ISSUE TITLE
pass web headers/environment to shell program

### ISSUE THREAD

**Issue by risacher** [chjj/tty.js#62]
Feature idea: I would like to be able to pass the information about the web environment to the shell program somehow (either as arguments or as environment variables)   

e.g. variables such as REMOTE_ADDR, HTTP_X_FORWARDED_FOR could be exposed to the underlying shell program.

Ultimately, I want my reverse proxy server to authenticate the user and pass a SAML assertion  (or equivalent) to tty.js, so the shell program can use upstream authentication.

**Comment by adamjimenez** [comment]
> @adamjimenez, depends on the client. This isn't limited to headers. You could parse a querystring for args if you wanted to.

I could but I want to re-use an existing socket in order to handle simultaneous connections.
